stages:
  - test

image: python:3-slim-buster

test:unit:
  stage: test
  script:
  - make venv
  - make unittest

test:integration:
  stage: test
  services:
  - eclipse-mosquitto
  script:
  - make venv
  - make integrationtest
