stages:
  - test

image: debian:testing-slim

test:unit:
  stage: test
  script:
  - apt-get update && apt-get install -y make python3 python3-venv python3-pip
  - make venv
  - make unittest

test:integration:
  stage: test
  services:
  - eclipse-mosquitto
  script:
  - apt-get update && apt-get install -y make python3 python3-venv python3-pip
  - make venv
  - make integrationtest
